### ISSUE TITLE
Final submission Final Project of XiangyuHan

### ISSUE THREAD

**Issue by clefthan** [QMSS-G5072-2021/Xiangyu-Han#10]
e4b756d
@QMSS-G5072-2021/teaching_team

**Comment by paolorivas** [comment]
Great job on your final project! Your total score is 92%. These are the details of your grading:

Scope, Complexity, and Mastery (40% of total): 4/5 
Coding Style (10% of total): 3/3
 Coding Strategy (10% of total): 3/3 
Packaging (40% of total): 
Structure: 3/3 
Docs: 3/3 
Ease of Access: 3/3
 Testing: 3/3 
Bonus: N/A

Notes:
Scope 4/5 means: This is a very good project. The difficulty or breadth of the functionality or data acquisition are substantially above average. Compared to excellent projects, however, complexity and difficulty are not equally developed. Also, the project individual complexity does not go beyond the class material. The tools and techniques from the course are applied very competently and creatively.
